CREATE SESSION to dms_aws;
GRANT SELECT ANY TRANSACTION TO dms_aws;
GRANT SELECT on V_$ARCHIVED_LOG TO dms_aws;
GRANT SELECT on V_$LOG TO dms_aws;
GRANT SELECT on V_$LOGFILE TO dms_aws;
GRANT SELECT on V_$DATABASE TO dms_aws;
GRANT SELECT on V_$THREAD TO dms_aws;
GRANT SELECT on V_$PARAMETER TO dms_aws;
GRANT SELECT on V_$NLS_PARAMETERS TO dms_aws;
GRANT SELECT on V_$TIMEZONE_NAMES TO dms_aws;
GRANT SELECT on V_$TRANSACTION TO dms_aws;
GRANT SELECT on ALL_INDEXES TO dms_aws;
GRANT SELECT on ALL_OBJECTS TO dms_aws;
GRANT SELECT on ALL_TABLES TO dms_aws;
GRANT SELECT on ALL_USERS TO dms_aws;
GRANT SELECT on ALL_CATALOG TO dms_aws;
GRANT SELECT on ALL_CONSTRAINTS TO dms_aws;
GRANT SELECT on ALL_CONS_COLUMNS TO dms_aws;
GRANT SELECT on ALL_TAB_COLS TO dms_aws;
GRANT SELECT on ALL_IND_COLUMNS TO dms_aws;
GRANT SELECT on ALL_LOG_GROUPS TO dms_aws;
GRANT SELECT on SYS.DBA_REGISTRY TO dms_aws;
GRANT SELECT on SYS.OBJ$ TO dms_aws;
GRANT SELECT on DBA_TABLESPACES TO dms_aws;
GRANT SELECT on ALL_TAB_PARTITION to dms_aws;

From R to Everyone 04:12 PM
1. Supplemental Log has to be enabled for the tables in the source. The statements used are as follows. 

ALTER DATABASE ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA; 
ALTER DATABASE FORCE LOGGING;

2. Establish A Connection : Execute the mentioned GRANT and SELECT statements

Example: GRANT SELECT ANY TRANSACTION TO SALES_TXN;

CREATE SESSION
GRANT SELECT ANY TRANSACTION TO 1. Supplemental Log has to be enabled for the tables in the source. The statements used are as follows. 

ALTER DATABASE ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA; 
ALTER DATABASE FORCE LOGGING;

2. Establish A Connection : Execute the mentioned GRANT and SELECT statements

Example: GRANT SELECT ANY TRANSACTION TO SALES_TXN;

CREATE SESSION
GRANT SELECT ANY TRANSACTION TO dms_aws;
GRANT SELECT on V_$ARCHIVED_LOG TO dms_aws;
GRANT SELECT on V_$LOG TO dms_aws;
GRANT SELECT on V_$LOGFILE TO dms_aws;
GRANT SELECT on V_$DATABASE TO dms_aws;
GRANT SELECT on V_$THR to to dms_aws;
