CREATE SESSION
GRANT SELECT ANY TRANSACTION TO AWS_USER;
GRANT SELECT on V_$ARCHIVED_LOG TO AWS_USER;
GRANT SELECT on V_$LOG TO AWS_USER;
GRANT SELECT on V_$LOGFILE TO AWS_USER;
GRANT SELECT on V_$DATABASE TO AWS_USER;
GRANT SELECT on V_$THREAD TO AWS_USER;
GRANT SELECT on V_$PARAMETER TO AWS_USER;
GRANT SELECT on V_$NLS_PARAMETERS TO AWS_USER;
GRANT SELECT on V_$TIMEZONE_NAMES TO AWS_USER;
GRANT SELECT on V_$TRANSACTION TO AWS_USER;
GRANT SELECT on ALL_INDEXES TO AWS_USER;
GRANT SELECT on ALL_OBJECTS TO AWS_USER;
GRANT SELECT on ALL_TABLES TO AWS_USER;
GRANT SELECT on ALL_USERS TO AWS_USER;
GRANT SELECT on ALL_CATALOG TO AWS_USER;
GRANT SELECT on ALL_CONSTRAINTS TO AWS_USER;
GRANT SELECT on ALL_CONS_COLUMNS TO AWS_USER;
GRANT SELECT on ALL_TAB_COLS TO AWS_USER;
GRANT SELECT on ALL_IND_COLUMNS TO AWS_USER;
GRANT SELECT on ALL_LOG_GROUPS TO AWS_USER;
GRANT SELECT on SYS.DBA_REGISTRY TO AWS_USER;
GRANT SELECT on SYS.OBJ$ TO AWS_USER;
GRANT SELECT on DBA_TABLESPACES TO AWS_USER;
GRANT SELECT on ALL_TAB_PARTITION
From R to Everyone 04:12 PM
1. Supplemental Log has to be enabled for the tables in the source. The statements used are as follows. 

ALTER DATABASE ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA; 
ALTER DATABASE FORCE LOGGING;

2. Establish A Connection : Execute the mentioned GRANT and SELECT statements

Example: GRANT SELECT ANY TRANSACTION TO SALES_TXN;

CREATE SESSION
GRANT SELECT ANY TRANSACTION TO 1. Supplemental Log has to be enabled for the tables in the source. The statements used are as follows. 

ALTER DATABASE ADD SUPPLEMENTAL LOG DATA (ALL) COLUMNS;
ALTER DATABASE ADD SUPPLEMENTAL LOG DATA; 
ALTER DATABASE FORCE LOGGING;

2. Establish A Connection : Execute the mentioned GRANT and SELECT statements

Example: GRANT SELECT ANY TRANSACTION TO SALES_TXN;

CREATE SESSION
GRANT SELECT ANY TRANSACTION TO AWS_USER;
GRANT SELECT on V_$ARCHIVED_LOG TO AWS_USER;
GRANT SELECT on V_$LOG TO AWS_USER;
GRANT SELECT on V_$LOGFILE TO AWS_USER;
GRANT SELECT on V_$DATABASE TO AWS_USER;
GRANT SELECT on V_$THR
